name: Test, build and publish Mozilla Firefox WebExtension
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Install web-ext
        run: npm install -g web-ext
      - name: Test
        run: web-ext lint
  
  build:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Install web-ext
        run: npm install -g web-ext
      - name: Build extension
        run: |
          web-ext build
          web-ext sign
      - name: Store build as artifact
        uses: actions/upload-artifact@v2
        with:
          name: tab-split-merger-build
          path: web-ext-artifacts

  publish:
    needs: [test,build]
    name: Publish the extension
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: tab-split-merger-build
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Install web-ext
        run: npm install -g web-ext
      - name: Sign extension
        run: web-ext sign --api-key ${{ secrets.WEBEXT_API_KEY }} --api-secret ${{ secrets.WEBEXT_API_SECRET }} --id ${{ secrets.WEBEXT_ID }}
        # uses: Saphareas/sign-web-extension-action@v0.1
        # with:
        #   web-ext-id: "{7f59e59d-6ece-4399-9c0d-b98d36c4db8c}"
        #   sign-listed: true
        #   amo-api-key: "user:15987920:706"
        #   amo-api-secret: "0ca7bd81835148b99f0309e193180cf59cc397caa836e0bf8b7de5f1f01d1d2f"
